### ISSUE TITLE
[Bug #5] Auto logged into admin account

### ISSUE THREAD

**Issue by Virnirr** [CSC307Fall2023/CodeNotes#27]
1. Select the correct branch (git checkout Jacobs-super-....)
2. Install all dependencies (npm install)
3. Startup backend (docker compose up)
4. Run application (npm run dev)

**Comment by jakethejrm** [comment]
I think this just has to do with how cookies in the browser work, and since they are all hosted on localhost:3000, and have somewhat similar login systems from the scaffolding at the beginning, it auto logs in, but I'm not too sure. I don't think we even had an admin account in our database.
